### ISSUE TITLE
Broken Linux Install

### ISSUE THREAD

**Issue by tboudreaux** [tboudreaux/fidanka#3]
On ubuntu 22.04 when running install in a fresh, python 3.10 anaconda venv

$ pip install .

the following error

              running build_ext
              building 'fidanka.ext.nearest_neighbors' extension
              Traceback (most recent call last):
                File "/home/tboudreaux/anaconda3/envs/py310/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
                  main()
                File "/home/tboudreaux/anaconda3/envs/py310/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
                  json_out['return_val'] = hook(**hook_input['kwargs'])
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/home/tboudreaux/anaconda3/envs/py310/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
                  return _build_backend().build_wheel(wheel_directory, config_settings,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
                  return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
                  self.run_setup()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
                  exec(code, locals())
                File "<string>", line 19, in <module>
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
                  return distutils.core.setup(**attrs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
                  return run_commands(dist)
                         ^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                  dist.run_commands()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                  self.run_command(cmd)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
                  super().run_command(command)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                  cmd_obj.run()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
                  self.run_command("build")
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                  self.distribution.run_command(command)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
                  super().run_command(command)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                  cmd_obj.run()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                  self.run_command(cmd_name)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                  self.distribution.run_command(command)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
                  super().run_command(command)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                  cmd_obj.run()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
                  _build_ext.run(self)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
                  self.build_extensions()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
                  self._build_extensions_serial()
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
                  self.build_extension(ext)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
                  _build_ext.build_extension(self, ext)
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
                  objects = self.compiler.compile(
                            ^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 590, in compile
                  macros, objects, extra_postargs, pp_opts, build = self._setup_compile(
                                                                    ^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 348, in _setup_compile
                  pp_opts = gen_preprocess_options(macros, incdirs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                File "/tmp/pip-build-env-ilrngg09/overlay/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1213, in gen_preprocess_options
                  pp_opts.append("-I%s" % dir)
                                 ~~~~~~~^~~~~
                File "<string>", line 7, in __str__
              ModuleNotFoundError: No module named 'numpy'
              [end of output]
  
        
        note: This error originates from a subprocess, and is likely not a problem with pip.
        
        ERROR: Failed building wheel for fidanka
        Failed to build fidanka
        ERROR: Could not build wheels for fidanka, which is required to install pyproject.toml-based projects

**Comment by tboudreaux** [comment]
Despite numpy being installed, this issue was caused by the ordering in which pip exposed things. Resolution in f7a638fe7600f01d3fbe61bd7acc65871ea9d7e7 by using numpy setup and Extension instead of setuptools in setup.py and by adding numpy before setuptools in the build-system requirements in pyproject.toml
